import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { useStore } from "./../../store";
import Head from "next/head";
import { getSingleProduct } from "@utils/api";
import { Product, Category } from "@utils/types";

export default function ProductDetail() {
  const router = useRouter();
  const { pid } = router.query;

  const [product, setProduct] = useState<Product>();

  useEffect(() => {
    getSingleProduct(Number(pid)).then((data) => setProduct(data));
  }, []);

  return (
    <>
      <Head>
        <title>Fake store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">{product?.title}</div>
      </main>
    </>
  );
}

// export const getStaticProps = async () => {
//   const [products, categories] = await Promise.all([
//     getAllProducts().then((data) => data),
//     getAllCategories().then((data) => data),
//   ]);

//   return {
//     props: {
//       products,
//       categories,
//     },
//   };
// };
