import { useState, useEffect } from "react";
import Head from "next/head";
import { getAllProducts } from "@utils/api";
import { Product } from "@utils/types";

import Searchbar from "@components/searchbar";

type Props = {
  products: Product[];
};

export default function Home({ products }: Props) {
  console.log(products);

  return (
    <>
      <Head>
        <title>Fake store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container"></div>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const products: Product[] = await getAllProducts().then((data) => data);

  return {
    props: {
      products,
    },
  };
};
